import type { Metadata } from 'next';
import { Nunito, Darker_Grotesque } from 'next/font/google';
import './globals.css';
import Provider from '@/components/Provider';
import TopNav from '@/components/navbar/TopNav';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'Dating App',
  description: 'Generated by create next app',
};

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito',
  display: 'swap',
});

const grotesque = Darker_Grotesque({
  subsets: ['latin'],
  variable: '--font-darker-grotesque',
  display: 'swap',
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const userId = session?.user?.id || null;
  const profileComplete = session?.user.profileComplete as boolean;
  return (
    <html lang='en'>
      <body className={`${nunito.variable} ${grotesque.variable} antialiased`}>
        <Provider userId={userId as string} profileComplete={profileComplete}>
          <TopNav />
          <div className='max-w-5xl mx-auto px-3 sm:px-6'>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
